### ISSUE TITLE
Autocompletion for Sublimetext2

### ISSUE THREAD

**Issue by erm3nda** [simple-mvc-framework/SMVC-Snippets#1]
I've put the snippets in my userdir and the most of them are not working.
As example, smcontroller and smcon works (using ctrl+space for autocompletion), but not the others.

I've not tested all the command cuz boring.
As example, smanyroute is not working.

Any suggestion?
Best regards.

**Comment by dcblogdev** [comment]
Hi they seem to be working for me, are you trying to use smanyroute in a .php file that has it's syntax set to php?
